/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bank_sampah;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Home_3 extends javax.swing.JFrame {

    /**
     * Creates new form Home_3
     */
    public Home_3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Minimize = new javax.swing.JLabel();
        jLabel_exit = new javax.swing.JLabel();
        jLabel_Minimize1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_tmpLogin = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jLabel_iconUser = new javax.swing.JLabel();
        jSeparator_Username = new javax.swing.JSeparator();
        jPasswordField_Login = new javax.swing.JPasswordField();
        jLabel_iconLogin = new javax.swing.JLabel();
        jSeparator_Password = new javax.swing.JSeparator();
        jButton_Login = new javax.swing.JButton();
        jLabel_toSignUp = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(360, 320));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Minimize.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel_Minimize.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Minimize.setText("-");
        jLabel_Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseClicked(evt);
            }
        });
        jPanel2.add(jLabel_Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, -1, 25));

        jLabel_exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_exit.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_exit.setText("X");
        jLabel_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
        });
        jPanel2.add(jLabel_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, -1, -1));

        jLabel_Minimize1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel_Minimize1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Minimize1.setText("Aplikasi Bank Sampah");
        jLabel_Minimize1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Minimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Minimize1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel_Minimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, 30));

        jPanel3.setBackground(new java.awt.Color(51, 102, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_tmpLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel_tmpLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_tmpLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_tmpLogin.setText("Login");
        jPanel3.add(jLabel_tmpLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, 340, -1));

        jTextField_Username.setBackground(new java.awt.Color(51, 102, 0));
        jTextField_Username.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField_Username.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Username.setText("Username");
        jTextField_Username.setBorder(null);
        jTextField_Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_UsernameFocusLost(evt);
            }
        });
        jPanel3.add(jTextField_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 126, 190, 30));

        jLabel_iconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_user_32px.png"))); // NOI18N
        jLabel_iconUser.setText("jLabel6");
        jPanel3.add(jLabel_iconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 30, 30));

        jSeparator_Username.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 190, 10));

        jPasswordField_Login.setBackground(new java.awt.Color(51, 102, 0));
        jPasswordField_Login.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField_Login.setText("Password");
        jPasswordField_Login.setBorder(null);
        jPasswordField_Login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_LoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_LoginFocusLost(evt);
            }
        });
        jPanel3.add(jPasswordField_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 190, 30));

        jLabel_iconLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_lock_32px_1_1.png"))); // NOI18N
        jLabel_iconLogin.setText("jLabel7");
        jPanel3.add(jLabel_iconLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 30, 30));

        jSeparator_Password.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 190, 10));

        jButton_Login.setBackground(new java.awt.Color(32, 32, 32));
        jButton_Login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Login.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Login.setText("LOGIN");
        jButton_Login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton_Login.setContentAreaFilled(false);
        jButton_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoginActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 240, 40));

        jLabel_toSignUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_toSignUp.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_toSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_toSignUp.setText("Don't have an account? Sign Up!");
        jLabel_toSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_toSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_toSignUpMouseClicked(evt);
            }
        });
        jPanel3.add(jLabel_toSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 240, -1));

        jPanel4.setPreferredSize(new java.awt.Dimension(850, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ffff.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 370, 570));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("\"Dulu Sampah, Sekarang Berkah\"");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 630, 580, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/unnamed1.jpg"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 730));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UsernameFocusGained
        /*Jika input text field berisi input kata "Username" maka
        input sebelumnya ditiadakan*/
        if(jTextField_Username.getText().trim().equals("Username")) {
            jTextField_Username.setText("");
        }
    }//GEN-LAST:event_jTextField_UsernameFocusGained

    private void jTextField_UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UsernameFocusLost
        /* Jika input text field belum diisi maka akan 
           diset default kata "Username" pada text field
        */
        if(jTextField_Username.getText().trim().equals("") || jTextField_Username.getText().trim().equals("Username")) {
            jTextField_Username.setText("Username");            
        }
        
    }//GEN-LAST:event_jTextField_UsernameFocusLost

    private void jPasswordField_LoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_LoginFocusGained
        /*Jika input Password field berisi input kata "Password" maka
        input sebelumnya ditiadakan*/
        String pass = String.valueOf(jPasswordField_Login.getPassword());
        
        if(pass.trim().equals("Password")) {
            jPasswordField_Login.setText("");
        }
                
    }//GEN-LAST:event_jPasswordField_LoginFocusGained

    private void jPasswordField_LoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_LoginFocusLost
        /* Jika input password field belum diisi maka akan 
           diset default kata "Password" pada Password field
        */
        String pass = String.valueOf(jPasswordField_Login.getPassword());
        
        if(pass.trim().equals("") || pass.trim().equals("Password")) {
            jPasswordField_Login.setText("Password");
        }
        
    }//GEN-LAST:event_jPasswordField_LoginFocusLost

    private void jLabel_MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseClicked
        // Berfungsi untuk melakukan minimize pada program
        this.setState(ICONIFIED);
        
    }//GEN-LAST:event_jLabel_MinimizeMouseClicked

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked
        // Berfungsi sebagai tombol exit
        System.exit(0);

    }//GEN-LAST:event_jLabel_exitMouseClicked

    private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoginActionPerformed
        
        PreparedStatement st;
        ResultSet rs;
        
        // Mendapatkan Username & Password
        String username = jTextField_Username.getText();
        String password = String.valueOf(jPasswordField_Login.getPassword());
        // Membuat query untuk cek apakah username dan password sudah ada
        String query = "SELECT * FROM `tb_user` WHERE `username` = ? AND `password` = ?";
        
        if(username.trim().equals("Username")) {
            // Tampilan peringatan jika username belum terisi
            JOptionPane.showMessageDialog(null, "Enter Your Username", "Empty username", 2);
        } else if(password.trim().equals("Password")) {
            // Tampilan peringatan jika password belum terisi
            JOptionPane.showMessageDialog(null, "Enter Your Password", "Empty password", 2);
        } else {
            try {
                st = Koneksi.getConnection().prepareStatement(query);

                st.setString(1, username);
                st.setString(2, password);
                rs = st.executeQuery();
            
                if(rs.next()) {
                    // new form
                    Kalkulator_1 form = new Kalkulator_1();
                    form.setVisible(true);
                    form.pack();
                    //close form
                    this.dispose();
                }else {
                    // Tampilan peringatan jika username / password invalid
                    JOptionPane.showMessageDialog(null, "Invalid Username / Password", "Login Error", 2);
                }           
            } catch (SQLException ex) {
                Logger.getLogger(Home_3.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_LoginActionPerformed

    private void jLabel_toSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_toSignUpMouseClicked
        // Berfungsi sebagai tombol untuk menuju form Sign Up
        Sign_Up3 sU = new Sign_Up3();
        sU.setVisible(true);
        sU.pack();
        sU.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel_toSignUpMouseClicked

    private void jLabel_Minimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Minimize1MouseClicked
        // Berfungsi untuk minimize program
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel_Minimize1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Minimize;
    private javax.swing.JLabel jLabel_Minimize1;
    private javax.swing.JLabel jLabel_exit;
    private javax.swing.JLabel jLabel_iconLogin;
    private javax.swing.JLabel jLabel_iconUser;
    private javax.swing.JLabel jLabel_tmpLogin;
    private javax.swing.JLabel jLabel_toSignUp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField_Login;
    private javax.swing.JSeparator jSeparator_Password;
    private javax.swing.JSeparator jSeparator_Username;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables
}
